CXX = g++
SOURCE_FILES = Queue.cpp Stack.cpp Combat.cpp Creature.cpp Barbarian.cpp BlueMen.cpp Goblin.cpp ReptilePeople.cpp TheShadow.cpp Die.cpp main.cpp

main: $(SOURCE_FILES)
	$(CXX) $(SOURCE_FILES) -o tournament

clean:
	rm tournament