CXX = g++

SOURCE_FILES = Character.cpp Space.cpp PlaneWorld.cpp LookingOutside.cpp Cockpit.cpp CaptainSeat.cpp FOSeat.cpp Forward.cpp FrontGalley.cpp FrontLav.cpp FirstClass.cpp ArnoldS.cpp JustinBieber.cpp Economy.cpp CryingBaby.cpp DroolingSleeper.cpp Back.cpp BackLav.cpp DrinkCart.cpp SecretCargo.cpp main.cpp

finalProject: $(SOURCE_FILES)
	$(CXX) $(SOURCE_FILES) $(CFLAGS) -o finalProject

clean:
	rm finalProject